### ISSUE TITLE
I can not logged Samsung Account in Certificate Manager

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#254] opened 2023-09-08 10:42 UTC
Hello. I want to create a certificate, but at the stage of logging into the Samsung account, there is just a white screen and the login page does not load. 2 weeks ago everything was loading. I also tried it in another country and on another computer.
![image](https://github.com/Samsung/Tizen.NET/assets/41239551/ea33201d-15c0-4a96-aefa-7f78be59fddd)
![image](https://github.com/Samsung/Tizen.NET/assets/41239551/1525221f-6f8f-4a9e-879b-f38b833d4a05)
![image](https://github.com/Samsung/Tizen.NET/assets/41239551/e24c01a6-e182-4eba-9587-263185e8ad34)

I also suggest to abandon the internal browser and do authorization in the default browser.

**Comment by skuzminov-softheme** [comment] 2023-09-10 19:57
In addition, I want to add that on Mac with Safari, it's possible to login into the account, but on the certificate signing it fails with the 401 error. The same account was fine two weeks ago on the Windows machine.

**Comment by dkson95** [comment] 2023-09-12 00:36
### Background
- This issue was caused by samsung account login module (recent patch update)
- IE and webkit legacy browser version (where Samsung Certificate are using) could not be supported anymore by sign-in process

### Solution
- Add HTTP redirect server, Launch browser and use httpserver to handle samsung account login


**The fix will be released by download.tizen.org to be updated by package manager. (due date: 15th, Sep)**

Thank you!

**Comment by dkson95** [comment] 2023-09-12 00:58
[tizen-certificate-extension_2.0.65.zip](https://download.tizen.org/sdk/extensions/tizen-certificate-extension_2.0.65.zip) uploaded to https://download.tizen.org/sdk/extensions/

**Closed by dkson95** 2023-09-12 00:58 UTC
Labels: sdk
